#!/bin/bash
set -x
#Test a single servere on another host later

PID0=
PID1=
PID2=
PID3=
#Start all replicas
./startcluster

#should succeed
 ./bin/kvs-client2 -h 127.0.0.1:9991 put 73 aaaa 1 

 sleep 1
#should return aaaa
 ./bin/kvs-client2 -h 127.0.0.1:9992 get 73 1
 sleep 1

#should succeed 
 ./bin/kvs-client2 -h 127.0.0.1:9992 put 73 bbbb 1
 sleep 1

#kill all and restart S2
./killservers
 sleep 1
./bin/kvs-server config.txt 1 >/dev/null 2>&1 &
PID1=$!
 sleep 1

#should return bbbb 
 ./bin/kvs-client2 -h 127.0.0.1:9992 get 73 1 
 sleep 1

#should fail
 ./bin/kvs-client2 -h 127.0.0.1:9992 put 137 ssss 1 

 sleep 1
#should fail because quorum cannot be achieved
 ./bin/kvs-client2 -h 127.0.0.1:9992 get 73 2
 sleep 1

#restart S3
./bin/kvs-server config.txt 2 >/dev/null 2>&1 &
PID2=$!
 sleep 1

#previous call should succeed now
 ./bin/kvs-client2 -h 127.0.0.1:9992 get 73 2
 sleep 1

#Start S1, S4 and stop S2
./bin/kvs-server config.txt 0 >/dev/null 2>&1 &
PID0=$!
 sleep 1
./bin/kvs-server config.txt 3 >/dev/null 2>&1 &
PID3=$!
 sleep 1
kill -9 $PID1

 sleep 1
#should be successfull storing a hint for S2 at S1 
 ./bin/kvs-client2 -h 127.0.0.1:9991 put 73 cccc 2
 sleep 1

#restart S2
./bin/kvs-server config.txt 1 >/dev/null 2>&1 &
PID1=$!
 sleep 1

#Store K3 = 243, Value = dddd 
 ./bin/kvs-client2 -h 127.0.0.1:9992 put 243 dddd 1 
 sleep 1

#Stop S3 and S4
kill -9 $PID2
kill -9 $PID3
 sleep 1

#Ask S1 for K1 with cLevel 1
 ./bin/kvs-client2 -h 127.0.0.1:9991 get 73 1
